name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: ".node-version"
          cache: true
      - run: vp install
      - run: vp check
      - run: vp build
  publish:
    if: github.ref == 'refs/heads/main'
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: ".node-version"
          cache: true
      - run: vp install
      - run: npx noeldemartin-publish-package
